import argparse
import json
import logging
import os
from pathlib import Path
from .data import make_demo, validate_csv
from .store import Store
from .pipeline import validate_training
from .service import train_run


def main():
    parser = argparse.ArgumentParser(description="ForecastLab — daily forecasting and planning")
    parser.add_argument("--data-dir", default=os.getenv("FORECASTLAB_DATA_DIR", "data"))
    sub = parser.add_subparsers(dest="command", required=True)
    serve = sub.add_parser("serve")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int, default=8000)
    demo = sub.add_parser("demo", help="Create synthetic data and train a complete demo")
    demo.add_argument("--horizon", type=int, default=14)
    train = sub.add_parser("train", help="Validate/import a CSV and run evaluation")
    train.add_argument("csv", type=Path)
    train.add_argument("--name", default="Imported daily data")
    train.add_argument("--horizon", type=int, default=14)
    train.add_argument("--provenance", type=Path, help="Optional JSON source/citation metadata")
    predict = sub.add_parser("predict", help="Reproduce forecasts from a trusted local model artifact")
    predict.add_argument("run_id")
    sync = sub.add_parser("sync-s3", help="Explicitly upload a completed run to your S3 bucket")
    sync.add_argument("run_id")
    sync.add_argument("--bucket", required=True)
    sync.add_argument("--prefix", default="forecastlab")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    root = Path(args.data_dir).resolve()
    root.mkdir(parents=True, exist_ok=True)
    if args.command == "serve":
        import uvicorn
        from .api import create_app
        uvicorn.run(create_app(root), host=args.host, port=args.port)
        return
    store = Store(os.getenv("DATABASE_URL", f"sqlite:///{root / 'forecastlab.db'}"))
    if args.command in ("demo", "train"):
        raw = make_demo().to_csv(index=False).encode() if args.command == "demo" else args.csv.read_bytes()
        try:
            df, quality = validate_csv(raw)
            validate_training(df, args.horizon)
        except ValueError as exc:
            parser.error(str(exc))
        if args.command == "train" and args.provenance:
            quality["provenance"] = json.loads(args.provenance.read_text())
        identity = store.add_dataset("Demo · digital demand" if args.command == "demo" else args.name,
                                    "synthetic-demo" if args.command == "demo" else ("public-dataset" if args.provenance else "user-upload"), df, quality)
        run = store.create_run(identity, args.horizon)
        train_run(store, root, run)
        result = store.get_run(run)
        print(json.dumps(result, indent=2))
        if result["status"] != "completed":
            raise SystemExit(1)
    else:
        run = store.get_run(args.run_id)
        if not run or run["status"] != "completed":
            parser.error("Completed run not found")
        directory = root / "runs" / args.run_id
        if args.command == "sync-s3":
            from .integrations import upload_s3
            print(json.dumps(upload_s3(directory, args.bucket, f"{args.prefix}/{args.run_id}"), indent=2))
        else:
            import joblib
            from .models import predict
            # Only load artifacts generated by this installation; pickle is unsafe for untrusted files.
            bundles = joblib.load(directory / "models.joblib")
            result = {name: predict(b["model_name"], b["model"], b["dates"], b["values"], b["horizon"]).tolist()
                      for name, b in bundles.items()}
            print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
